[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_swap = "HyJPnD797BzhzkLGfDYbt4qVyghsYkTZtJX8ipb6qABT"

[programs.devnet]
solana_swap = "HyJPnD797BzhzkLGfDYbt4qVyghsYkTZtJX8ipb6qABT"

[programs.testnet]
solana_swap = "HyJPnD797BzhzkLGfDYbt4qVyghsYkTZtJX8ipb6qABT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/thanhlevan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
